import * as React from "react";

export const initialProductState = [
  {
    id: 1,
    name: "Honeycomb purple",
    description: "Purple magic honeycomb, great thing",
    barcode: "honeycomb:honeycombpurple",
    imageSrc: "1.png",
    itemType: 1,
  },
  {
    id: 2,
    name: "Honeycomb green",
    description: "Green honeycomb, great thing!",
    barcode: "honeycomb:honeycombgreen",
    imageSrc: "2.png",
    itemType: 1,
  },
  {
    id: 3,
    name: "Bee net",
    description: "Bee net for bee hunting. Great one!",
    barcode: "tools:beenet",
    imageSrc: "3.png",
    itemType: 2,
  },
  {
    id: 4,
    name: "Black-yellow bee",
    description: "Small bee. They not brings honey",
    barcode: "bee:blackyellowbee",
    imageSrc: "4.png",
    itemType: 3,
  },
  {
    id: 5,
    name: "Queen-yellow bee",
    description: "Small bee. They not brings honey",
    barcode: "bee:queenyellowbee",
    imageSrc: "5.png",
    itemType: 3,
  },
  {
    id: 6,
    name: "King-yellow bee",
    description: "Small bee. They not brings honey",
    barcode: "bee:kingyellowbee",
    imageSrc: "4.png",
    itemType: 3,
  },
  {
    id: 7,
    name: "Queen-green bee",
    description: "Small bee. They not brings honey",
    barcode: "bee:queengreenbee",
    imageSrc: "4.png",
    itemType: 3,
  },
  {
    id: 8,
    name: "King-green bee",
    description: "Small bee. They not brings honey",
    barcode: "bee:kinggreenbee",
    imageSrc: "4.png",
    itemType: 3,
  },
  {
    id: 9,
    name: "Funcing salve bee",
    description: "Small bee. They not brings honey",
    barcode: "bee:funcingsalvebee",
    imageSrc: "4.png",
    itemType: 3,
  },
];
