import * as React from "react";

export const initialProductState = [
  {
    id: 1,
    name: "Honeycomb purple",
    description: "Purple magic honeycomb, great thing",
    barcode: "honeycomb:honeycombpurple",
    picturePath: "1.png",
    shopItemTypeId: 1,
    cost: 100,
  },
  {
    id: 2,
    name: "Honeycomb green",
    description: "Green honeycomb, great thing!",
    barcode: "honeycomb:honeycombgreen",
    picturePath: "2.png",
    shopItemTypeId: 1,
    cost: 100,
  },
  {
    id: 3,
    name: "Bee net",
    description: "Bee net for bee hunting. Great one!",
    barcode: "tools:beenet",
    picturePath: "3.png",
    shopItemTypeId: 2,
    cost: 100,
  },
  {
    id: 4,
    name: "Black-yellow bee",
    description: "Small bee. They not brings honey",
    barcode: "bee:blackyellowbee",
    picturePath: "4.png",
    shopItemTypeId: 3,
    cost: 100,
  },
  {
    id: 5,
    name: "Queen-yellow bee",
    description: "Small bee. They not brings honey",
    barcode: "bee:queenyellowbee",
    picturePath: "5.png",
    shopItemTypeId: 3,
    cost: 100,
  },
  {
    id: 6,
    name: "King-yellow bee",
    description: "Small bee. They not brings honey",
    barcode: "bee:kingyellowbee",
    picturePath: "4.png",
    shopItemTypeId: 3,
    cost: 100,
  },
  {
    id: 7,
    name: "Queen-green bee",
    description: "Small bee. They not brings honey",
    barcode: "bee:queengreenbee",
    picturePath: "4.png",
    shopItemTypeId: 3,
    cost: 100,
  },
  {
    id: 8,
    name: "King-green bee",
    description: "Small bee. They not brings honey",
    barcode: "bee:kinggreenbee",
    picturePath: "4.png",
    shopItemTypeId: 3,
    cost: 100,
  },
  {
    id: 9,
    name: "Funcing salve bee",
    description: "Small bee. They not brings honey",
    barcode: "bee:funcingsalvebee",
    picturePath: "4.png",
    shopItemTypeId: 3,
    cost: 100,
  },
];
